version: '3.3'
services:
  mail-bridge.as:
    build: .
    container_name: mail-bridge
    ports:
      - 8001:80
    volumes:
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ..:/var/www/html
    environment:
      - environment=prod
