version: '3.3'
services:
  imap.as:
    build: .
    container_name: imap.as
    ports:
      - 8001:80
    volumes:
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ../../orm/:/var/www/orm
      - ..:/var/www/html
    environment:
      - SYNAPSE=synapse

networks:
  default:
    external:
      name: dev-net
