
# matrix server url
matrixUrl: http://localhost:8008

# the token for identification with the matrix server
tokenMine: wfghWEGh3wgWHEf3478sHFWF

# tokens from guests this services will talk with
tokenGuest:
    - ugw8243igya57aaABGFfgeyu

# matrix server domain
domain: syntest.lan

# encryption key for account data
key: n4Kbu29Ycc8EG2d23myHBQMUcEHeUDIwKB9OiPbT0kc=

# name of the cookie
cookieName: mailBridge

# name of the pid file
pidFile: /var/tmp/mxmail.pid

# Root of file store
fileStoreRoot: /tmp/mail
